CREATE PROC FI_SP_ConsPeloClienteBeneficiario
	@IDCLIENTE BIGINT
AS
BEGIN
	IF(ISNULL(@IDCLIENTE, 0) = 0)
	BEGIN
		SELECT NOME, CPF, IDCLIENTE, ID 
		FROM BENEFICIARIOS WITH(NOLOCK);
	END
	ELSE
	BEGIN
		SELECT NOME, CPF, IDCLIENTE, ID 
		FROM BENEFICIARIOS WITH(NOLOCK) 
		WHERE IDCLIENTE = @IDCLIENTE;
	END
END
